#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-neighbr
Version  : 1.0.3
Release  : 11
URL      : https://cran.r-project.org/src/contrib/neighbr_1.0.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/neighbr_1.0.3.tar.gz
Summary  : Classification, Regression, Clustering with K Nearest Neighbors
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : buildreq-R

%description
algorithm. Implements several distance and similarity measures, covering
    continuous and logical features. Outputs ranked neighbors. Most features of
    this package are directly based on the PMML specification for KNN.

%prep
%setup -q -c -n neighbr
cd %{_builddir}/neighbr

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641066109

%install
export SOURCE_DATE_EPOCH=1641066109
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library neighbr
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library neighbr
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library neighbr
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc neighbr || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/neighbr/DESCRIPTION
/usr/lib64/R/library/neighbr/INDEX
/usr/lib64/R/library/neighbr/Meta/Rd.rds
/usr/lib64/R/library/neighbr/Meta/features.rds
/usr/lib64/R/library/neighbr/Meta/hsearch.rds
/usr/lib64/R/library/neighbr/Meta/links.rds
/usr/lib64/R/library/neighbr/Meta/nsInfo.rds
/usr/lib64/R/library/neighbr/Meta/package.rds
/usr/lib64/R/library/neighbr/Meta/vignette.rds
/usr/lib64/R/library/neighbr/NAMESPACE
/usr/lib64/R/library/neighbr/NEWS.md
/usr/lib64/R/library/neighbr/R/neighbr
/usr/lib64/R/library/neighbr/R/neighbr.rdb
/usr/lib64/R/library/neighbr/R/neighbr.rdx
/usr/lib64/R/library/neighbr/doc/index.html
/usr/lib64/R/library/neighbr/doc/neighbr-help.R
/usr/lib64/R/library/neighbr/doc/neighbr-help.Rmd
/usr/lib64/R/library/neighbr/doc/neighbr-help.html
/usr/lib64/R/library/neighbr/help/AnIndex
/usr/lib64/R/library/neighbr/help/aliases.rds
/usr/lib64/R/library/neighbr/help/neighbr.rdb
/usr/lib64/R/library/neighbr/help/neighbr.rdx
/usr/lib64/R/library/neighbr/help/paths.rds
/usr/lib64/R/library/neighbr/html/00Index.html
/usr/lib64/R/library/neighbr/html/R.css
/usr/lib64/R/library/neighbr/tests/testthat.R
/usr/lib64/R/library/neighbr/tests/testthat/test_comparison_measures.R
/usr/lib64/R/library/neighbr/tests/testthat/test_knn.R
/usr/lib64/R/library/neighbr/tests/testthat/test_knn_input_check.R
/usr/lib64/R/library/neighbr/tests/testthat/test_utility_functions.R
